#!/usr/bin/env bash

curl -o $HOME/shs/change/changew_inicio.info "$1"
compare() {
    if [ -n "$(diff $HOME/shs/change/changew_inicio.info $HOME/shs/change/changew_depois.info)" ];
    then
	notify-send "o site \"$1\" mudou"
	exit
    fi
}
while true;
do
    $(curl -o $HOME/shs/change/changew_depois.info "$1") && compare
done
