#!/bin/bash

# Play a radio station

Radio=$(ls --hide=*.sh $HOME/Music/radio/ | dmenu -f -i -p 'listen to Radio' )

if [ -n "$(echo $Radio | grep "\.txt")" ]; then
    mpv --volume=60 --no-video "$(cat $HOME/Music/radio/$Radio)"
else
    mpv --volume=60 --no-video "$Radio"
fi
