#!/bin/bash

# YT playlist in shuffle

mpv --volume=60 --no-video --shuffle "$(cat $HOME/settings/link_yt_playlist.info)"
# mpv -vo=caca --no-video --shuffle "$(cat $HOME/settings/link_yt_playlist.info)"
