#!/bin/bash

index () {
	yt-dlp --flat-playlist --print "\"%(title)s\" $(printf "\t"), https://www.youtube.com/watch?v=%(id)s" "$(cat $HOME/settings/link_yt_playlist.info)" | \
		cat -n | \
		tee $HOME/settings/songs_data.csv | \
		cut -f 1,2 | \
		dmenu -l 35 -f -i -p "Vid: " | \
		grep -o "[0-9]*"
}

mpv --no-video --playlist-start $(($(index) -1))

# link () {
# 	sed -n $(index)p $HOME/settings/songs_data.csv | grep -o "https://www.youtube.com.*"
# }
#
# mpv --no-video $(link)
