#!/bin/bash

if grep -q "$(ls)" <(echo "$@");
then
	calc="$(echo $@ | sed "s/$(ls | tr "\n" " ")/\*/g")"
else 
	calc=$@
fi

# Comverting XXmin XXh XXs to seconds
# and XXp = XX periods ( 1p = 50 min ) 
if grep -q "[0-9]* *s" <(echo "$@")
then 
	calc="$(echo $@ | sed 's/\([0-9]*\) *s/ \1 /g')"

elif grep -q "[0-9]* *min" <(echo "$@")
then 
	calc="$(echo $@ | sed 's/\([0-9]*\) *min/ \1 \* 60 /g')"

elif grep -q "[0-9]* *h" <(echo "$@")
then 
	calc="$(echo $@ | sed 's/\([0-9]*\) *h/ \1 \* 60 \* 60 /g')"
	
elif grep -q "[0-9]* *p" <(echo "$@")
then 
	calc="$(echo $@ | sed 's/\([0-9]*\) *p/ \1 \* 60 \* 50 /g')"
	
fi

time_end="$(($calc))"

toilet_font="pagga.tlf"

printf "\r%02d:%02d:%02d\n" "$((time_end / 60 / 60))" "$((time_end / 60 % 60))" "$((time_end % 60))" | toilet -f $toilet_font


temp_file=$(mktemp)
echo "string,ç[}jg´" | toilet -w 99999999 -f $toilet_font > $temp_file
height_of_toilet_font="$(($(wc -l $temp_file | sed 's/\(^[0-9]*\) .*$/\1/')))"
# height_of_toilet_font=3
spacing(){
	for ((i=0;i<$height_of_toilet_font;i++));
	do
		echo # new line
	done
}
spacing

key_press () {
	while true; do
		read -t 1 -N 1 -s -r && spacing && break
	done
}

clean_term(){
	i=0
	for ((i=0;i<$height_of_toilet_font;i++)); 
	do
		printf "\r\033[A\r"
	done
}

s=$time_end
n_pauses=1
while :
do 
	if (( s <= 0 ))
	then 
		break
	fi

	clean_term

	printf "%02d:%02d:%02d" "$((s / 60 / 60))" "$((s / 60 % 60))" "$((s % 60))" | toilet -f $toilet_font
	# If the hour gets bigger than 2 digits, it will grow to fit, it will not "cut" the last/first digit(s) off.

	read -t 1 -N 1 -s -r key && clean_term && printf "\r%02d:%02d:%02d [ Paused %d - %s ]" "$((s / 60 / 60))" "$((s / 60 % 60))" "$((s % 60))" "$n_pauses" "$(date +'%H:%M:%S')" | toilet -w $COLUMNS -f $toilet_font && key_press && ((s++)) && ((n_pauses++))

	((s--))
done

echo # New line
mpv --loop=inf $HOME/settings/censor-beep-3.mp3
